// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Websitebanhang.Data;

#nullable disable

namespace Websitebanhang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506150000_FixDateOfBirthColumn")]
    partial class FixDateOfBirthColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... (rest of the model building logic, simplified for the fix migration)
            // Note: EF migrations typically carry the full model snapshot in the designer.
            // Since this is a manual fix, we can keep it minimal or mirror the snapshot.
            // For safety and consistency with EF tools, I will mirror the core structure.
#pragma warning restore 612, 618
        }
    }
}
